### ISSUE TITLE
Can't destroy/modify IPSec tunnels

### ISSUE THREAD

**Issue by TwoStepz** [PaloAltoNetworks/terraform-provider-scm#11]
## Describe the bug

Can't destroy/modify an IPSec tunnel as it won't use the "folder" attribute when performing the API call

## Expected behavior

Terraform destroy should be able to remove IPSec tunnels

## Current behavior

IPSec tunnels can be created via the "scm_ipsec_tunnel" resource, but can't be destroyed/modified

## Steps to reproduce

1. Create an ipsec tunnel using the "scm_ipsec_tunnel" resource
2. Include the folder parameter
3. Perform a `terraform apply` command
4. Then try to perform a `terraform destroy` command
5. You'll get the following error: 
`[HTTP 400] API_I00035 Invalid Request Payload [object Object] - ["folder" is required]`

## Screenshots

Terraform file structure using the "scm_ipsec_tunnel" resource and referecing the "folder" attribute
![Screenshot 2024-02-13 at 7 35 15 PM](https://github.com/PaloAltoNetworks/terraform-provider-scm/assets/49874991/255d53d1-cb53-42b5-a50d-d9bfd2a4a1c2)

Errors when trying to execute a "terraform destroy" command, even when having the "folder" attribute on the terraform file
<img width="630" alt="Screenshot 2024-02-12 at 9 29 43 PM" src="https://github.com/PaloAltoNetworks/terraform-provider-scm/assets/49874991/f31cee75-e74c-42d9-a551-9ba82f614aaf">

## Context

I'm trying to standardize the Remote Network configuration for a customer

## Your Environment

- Version used: Terraform provider 0.1.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Terraform v1.7.2
- Operating System and version (desktop or mobile): Desktop MacOS Sonoma
- Link to your project: N/A

**Comment by ancoleman** [comment]
@TwoStepz this should now be fixed in [@v0.4.0](https://github.com/PaloAltoNetworks/terraform-provider-scm/releases/tag/v0.4.0) please test for yourself. If everything is good, report back and this will be closed.

**Comment by shinmog** [comment]
seems to be fixed, closing this issue
