### ISSUE TITLE
Support for URL Categories

### ISSUE THREAD

**Issue by murathatipoglu** [PaloAltoNetworks/terraform-provider-scm#18]
### Is your feature request related to a problem?

Latest version of the provider (0.6.0) lack of support for URL Categories.

### Describe the solution you'd like

Add support for URL Categories which are consumed in URL Access Profiles which is already supported by the provider.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by ancoleman** [comment]
@murathatipoglu please find the feature enhancement in release v.0.7.0 with commit e2b879c

**Comment by ancoleman** [comment]
Please confirm on your side that it works and I will close the request.

**Comment by murathatipoglu** [comment]
> Please confirm on your side that it works and I will close the request.

Hi Anton (@ancoleman)

I appreciate your quick and prompt action on this request. 

The new scm_url_category resource worked pretty well adn as intented. I am able to create all our URL categories through TF code.

Great work! Cheers.

**Comment by ancoleman** [comment]
completed with e2b879c
