### ISSUE TITLE
`scm_service_connection` gives error when explicit provider host is not set

### ISSUE THREAD

**Issue by zbuchheit** [PaloAltoNetworks/terraform-provider-scm#19]
## Describe the bug

When attempting to use the `scm_service_connection` resource or data object, I get an `object not found` error. 

When looking at the logs I noticed when `host` isn't set the api call is made to `Host: api.strata.paloaltonetworks.com` which I would expect it to actually be `api.sase.paloaltonetworks.com`. When I set the host on the provider it is able to make the api call correctly.

## Expected behavior

Create or query a service connection resource correctly without error.

## Current behavior

Encountering an error 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error reading config
│ 
│   with data.scm_service_connection.example,
│   on main.tf line 15, in data "scm_service_connection" "example":
│   15: data "scm_service_connection" "example" {
│ 
│ object not found
```

## Steps to reproduce

<details><summary>TF Repro File</summary>

```
terraform {
  required_providers {
    scm = {
      source  = "paloaltonetworks/scm"
      version = "0.9.2"
    }
  }
}

provider "scm" {
  logging = "detailed"
#   host = "api.sase.paloaltonetworks.com"
}

data "scm_service_connection" "example" {
   id = "REDACTED"
   folder= "Service Connections"
}
```
</details>

1. Create a service connection manually (or alternatively attempt to create one) without host set on the provider
2. Run `terraform plan`
3. Witness error
4. Set host to be "api.sase.paloaltonetworks.com"
5. Witness successful run

## Context

I am also witnessing this behavior with remote_networks. I suspect this might be coming from [this line](https://github.com/PaloAltoNetworks/scm-go/blob/5a26fd830249a321b30eb094c3e5d6d2a4808eb3/client.go#L131)

## Your Environment

- Version used: 0.9.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by shinmog** [comment]
The documentation for the default value for the "host" param within the provider block was incorrect.  The default value for "host" is "[api.strata.paloaltonetworks.com](http://api.strata.paloaltonetworks.com/)", so the documentation for this can be updated to reflect the correct default value.

**Comment by zbuchheit** [comment]
closing as this is by design. Thanks!
