### ISSUE TITLE
`scm_remote_network` gives an error when explicit provider host is not set

### ISSUE THREAD

**Issue by zbuchheit** [PaloAltoNetworks/terraform-provider-scm#20]
## Describe the bug

When attempting to use the `scm_remote_network` resource or data object, I get an `object not found` error. 

When looking at the logs I noticed when `host` isn't set the api call is made to `Host: api.strata.paloaltonetworks.com` which I would expect it to actually be `api.sase.paloaltonetworks.com`. When I set the host on the provider it is able to make the api call correctly. I suspect this might be coming from the scm-go library somehow setting an incorrect default for certain resources. I also witness this behavior with `scm_service_connection`

## Expected behavior

Create or query a remote network resource correctly without error

## Current behavior

I encounter a object not found error

## Possible solution

I suspect this is related to https://github.com/PaloAltoNetworks/terraform-provider-scm/issues/19 as it is the same behavior

## Steps to reproduce

1. Create a remote network manually (or alternatively attempt to create one) without host set on the provider
2. Run `terraform plan`
3. Witness error
4. Set provider host to be "api.sase.paloaltonetworks.com"
5. Witness successful run

## Your Environment

- Version used: 0.9.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by shinmog** [comment]
The documentation for the default value for the "host" param within the provider block was incorrect.  The default value for "host" is "[api.strata.paloaltonetworks.com](http://api.strata.paloaltonetworks.com/)", so the documentation for this can be updated to reflect the correct default value.

**Comment by zbuchheit** [comment]
ah so this is working as intended/expected?

**Comment by shinmog** [comment]
Yes, the intended behavior is that the `host` param defaults to "api.strata.paloaltonetworks.com".

**Comment by zbuchheit** [comment]
closing as this works as intended. Thanks!
