### ISSUE TITLE
resource scm_app_override_rule string to int64 conversion errors on apply

### ISSUE THREAD

**Issue by ancoleman** [PaloAltoNetworks/terraform-provider-scm#7]
## Describe the bug

When attempting to generate the **resource**: _scm_app_override_rule_ the rules are generated but an error occurs during the apply. This is possibly an issue with the API itself. The bug is specific to the port parameter. You can directly add the integer value to the resource and the problem will occur. Review the current behavior section for error.

## Expected behavior

The resource should build without errors. Because the resource builds correctly on the SCM tenant, the assumption is in the post- processing response from the API.

## Current behavior
```stdout
╷
│ Error: Error creating config
│ 
│   with module.security_policy_with_yaml.scm_app_override_rule.this["terraform-app-override-rule-3"],
│   on ../../modules/policy/rules.tf line 131, in resource "scm_app_override_rule" "this":
│  131: resource "scm_app_override_rule" "this" {
│ 
│ json: cannot unmarshal string into Go struct field Config.port of type int64
╵
╷
│ Error: Error creating config
│ 
│   with module.security_policy_with_yaml.scm_app_override_rule.this["terraform-app-override-rule-1"],
│   on ../../modules/policy/rules.tf line 131, in resource "scm_app_override_rule" "this":
│  131: resource "scm_app_override_rule" "this" {
│ 
│ json: cannot unmarshal string into Go struct field Config.port of type int64
╵
╷
│ Error: Error creating config
│ 
│   with module.security_policy_with_yaml.scm_app_override_rule.this["terraform-app-override-rule-2"],
│   on ../../modules/policy/rules.tf line 131, in resource "scm_app_override_rule" "this":
│  131: resource "scm_app_override_rule" "this" {
│ 
│ json: cannot unmarshal string into Go struct field Config.port of type int64
╵
```

## Steps to reproduce

Resource example:

```hcl
resource "scm_app_override_rule" "this" {
  for_each           = try(var.app_override_rules, {})
  folder             = try(each.value.folder, null) # Required
  name               = each.key                     # Required
  position           = try(each.value.position, "pre")
  description        = try(each.value.description, null)
  application        = try(each.value.application, null) # Required
  destinations       = length(local.app_destination_list[each.key]) == 0 ? ["any"] : local.app_destination_list[each.key]
  sources            = length(local.app_source_list[each.key]) == 0 ? ["any"] : local.app_source_list[each.key] # Source Regions not supported
  port               = 443                                                    # Required
  protocol           = try(each.value.protocol, null)                                                           # Required
  tos                = try(each.value.to, ["untrust"])                                                          # Required
  froms              = try(each.value.from, ["trust"])                                                          # Required
  disabled           = try(each.value.disabled, false)
  group_tag          = try(each.value.group_tag, null)
  negate_destination = try(each.value.negate_destination, false)
  negate_source      = try(each.value.negate_source, false)
  tags               = try(each.value.tags, null)
  device             = null
  snippet            = null
  depends_on = [
    scm_tag.this,
    scm_address_object.this,
    scm_address_group.this,
    scm_external_dynamic_list.this
  ]
}
```

## Context

This renders the _scm_app_override_rule_ resource useless.

## Your Environment

- Version used: Terraform v1.4.6
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile): MacOS Sonoma 14.2
- Link to your project:

**Comment by shinmog** [comment]
This is a bug with Strata Cloud Manager.  They are returning a `string` instead of a number.

I could change this on my side, changing `port` from an int to a string, but then we'd lose the range validation that is done, so this feels like a downgrade in functionality that I don't think I should do.

Going to close this out as the provider is behaving properly, the API is at fault.

**Comment by ancoleman** [comment]
If we leave this unfixed, the resource can’t be used. So we should either
remove support, fix it, or push for a fix in the API asap.

Anton Coleman  | Global Solutions Architect - Automation

Palo Alto Networks  |  3000 Tannery Way  |  Santa Clara, CA 95054  |  USA

Mobile: 931.267.5326  | www.paloaltonetworks.com



<https://www.paloaltonetworks.com/prisma>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.
